name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Get version from VERSION file
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t gland_qiu .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag gland_qiu ${{ secrets.DOCKER_USERNAME }}/gland_qiu:latest
          docker tag gland_qiu ${{ secrets.DOCKER_USERNAME }}/gland_qiu:${{ env.VERSION }}
          docker tag gland_qiu ${{ secrets.DOCKER_USERNAME }}/gland_qiu:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gland_qiu:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gland_qiu:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/gland_qiu:${{ github.sha }}

      - name: Clean up
        run: docker system prune -f
